# Generated by Django 5.2.1 on 2025-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.CharField(blank=True),
        ),
    ]
