# Generated by Django 5.2.1 on 2025-05-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_myuser_description_alter_myuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Пользователи'},
        ),
    ]
