# Generated by Django 5.2.1 on 2025-05-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_alter_myuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
