# Generated by Django 5.1.4 on 2025-05-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='пункт меню')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('under_menu', models.ManyToManyField(blank=True, null=True, related_name='+', to='auto_menu.menu', verbose_name='под уровень')),
            ],
        ),
    ]
