# Generated by Django 5.1.4 on 2025-05-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='above_menu',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='auto_menu.menu', verbose_name='начальник'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='under_menu',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='auto_menu.menu', verbose_name='подчинённые'),
        ),
    ]
