# Generated by Django 5.1.4 on 2025-05-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_menu', '0003_alter_menu_above_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='under_menu',
            field=models.ManyToManyField(blank=True, null=True, to='auto_menu.menu', verbose_name='подчинённые'),
        ),
    ]
