# Generated by Django 5.1.4 on 2025-05-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_menu', '0004_alter_menu_under_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='above_menu',
        ),
    ]
