# Generated by Django 5.1.4 on 2025-05-16 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_menu', '0005_remove_menu_above_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='under_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='under_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='auto_menu.menu', verbose_name='подчинённые'),
        ),
    ]
