# Generated by Django 5.1.4 on 2025-05-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_menu', '0007_remove_menu_under_menu_menu_main_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='main_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_menu.menu', verbose_name='Начальник'),
        ),
    ]
