# Generated by Django 5.1.4 on 2025-05-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_menu', '0008_alter_menu_main_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='point_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default='main_menu', max_length=200, verbose_name='название меню'),
        ),
    ]
