# Generated by Django 6.0a1 on 2025-10-09 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('link_to_the_original', models.URLField(blank=True, null=True, verbose_name='Ссылка на оригинал')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='DeveloperOfTheCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link_to_the_original', models.URLField(blank=True, null=True, verbose_name='Ссылка на оригинал')),
            ],
            options={
                'verbose_name': 'Автор курса',
                'verbose_name_plural': 'Авторы курсов',
            },
        ),
        migrations.CreateModel(
            name='Passion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Увлечение',
                'verbose_name_plural': 'Увлечения',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.CharField(blank=True, choices=[('JN', 'базовый'), ('MD', 'средний'), ('SN', 'продвинутый')], max_length=2, null=True, verbose_name='Уровень владения навыком')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link_to_the_original', models.URLField(blank=True, null=True, verbose_name='Ссылка на оригинал')),
                ('date', models.DateField(verbose_name='Дата получения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificate/', verbose_name='Изображение')),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='resume_app.course', verbose_name='Где получен')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='the_author_is_a_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume_app.developerofthecourse', verbose_name='Автор или разработчик'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя (для анонимов)')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Идентификатор объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Отредактировано')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('pending', 'На модерации'), ('hidden', 'Скрыто')], default='published', max_length=20, verbose_name='Статус')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Модель привязки')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='used_skills',
            field=models.ManyToManyField(blank=True, related_name='courses', to='resume_app.skill', verbose_name='Приобретённые навыки'),
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('link_to_the_original', models.URLField(blank=True, null=True, verbose_name='Ссылка на оригинал')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('used_skills', models.ManyToManyField(blank=True, related_name='i_worked_for', to='resume_app.skill', verbose_name='Навыки полученные на этой работе')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('link_to_the_original', models.URLField(blank=True, null=True, verbose_name='Ссылка на оригинал')),
                ('used_skills', models.ManyToManyField(blank=True, related_name='projects', to='resume_app.skill', verbose_name='В проекте использованы навыки')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='resume_app.working', verbose_name='Рабочее место проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
