# Generated by Django 5.2.1 on 2025-05-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_menu', '0002_alter_menu_under_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='under_menu',
        ),
        migrations.CreateModel(
            name='UnderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('under_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auto_menu.undermenu', verbose_name='Она же')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='under_menu',
            field=models.ManyToManyField(to='auto_menu.undermenu'),
        ),
    ]
