# Generated by Django 5.2.1 on 2025-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_menu', '0003_remove_menu_under_menu_undermenu_menu_under_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undermenu',
            name='under_menu',
        ),
        migrations.AddField(
            model_name='undermenu',
            name='under_menu',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='auto_menu.undermenu', verbose_name='Она же'),
        ),
    ]
