# Generated by Django 5.2.1 on 2025-05-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_menu', '0004_remove_undermenu_under_menu_undermenu_under_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(verbose_name='пункт меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='under_menu',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='auto_menu.menu', verbose_name='под уровень'),
        ),
        migrations.DeleteModel(
            name='UnderMenu',
        ),
    ]
