# Generated by Django 5.2.1 on 2025-05-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_menu', '0005_alter_menu_name_alter_menu_under_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
