# Generated by Django 5.2.1 on 2025-05-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_menu', '0007_alter_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
