# Generated by Django 5.2.2 on 2025-06-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_city_countryofconsignment_profession_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Название города', 'verbose_name_plural': 'Названия городов'},
        ),
        migrations.AlterModelOptions(
            name='countryofconsignment',
            options={'ordering': ['name'], 'verbose_name': 'Название страны', 'verbose_name_plural': 'Названия стран'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['name'], 'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='Обо мне'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new.countryofconsignment', verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new.organization', verbose_name='Текущее место работы'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='motto',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Мой девиз'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_s_photo/', verbose_name='Собственное изображение'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new.profession', verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='the_level_of_professionalism',
            field=models.CharField(blank=True, choices=[(1, 'ученик'), (2, 'начинающий'), (3, 'небольшой опыт'), (4, 'опыт есть'), (5, 'профессионал'), (6, 'супер-профессионал'), (7, 'хобби')], max_length=1, null=True, verbose_name='Уровень профессионализма'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='countryofconsignment',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='countryofconsignment',
            name='state_flag',
            field=models.ImageField(blank=True, null=True, upload_to='flag/', verbose_name='Государственный флаг'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
