# Generated by Django 5.2.2 on 2025-06-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='the_level_of_professionalism',
            field=models.CharField(blank=True, choices=[('LR', 'ученик'), ('BR', 'начинающий'), ('LL', 'небольшой опыт'), ('EX', 'опыт есть'), ('PR', 'профессионал'), ('SP', 'супер-профессионал'), ('HB', 'хобби')], max_length=2, null=True, verbose_name='Уровень профессионализма'),
        ),
    ]
