# Generated by Django 5.2.2 on 2025-06-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_alter_myuser_the_level_of_professionalism'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='biological_sex',
            field=models.CharField(blank=True, choices=[('F', 'женский'), ('M', 'мужской')], max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
