# Generated by Django 5.2.2 on 2025-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0007_supplementprofession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplementprofession',
            name='supplement_the_profession_of_the_user',
        ),
        migrations.AddField(
            model_name='profession',
            name='supplement_the_profession_of_the_user',
            field=models.ManyToManyField(related_name='supplement', to='new.supplementprofession'),
        ),
    ]
