# Generated by Django 5.2.2 on 2025-07-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0008_remove_supplementprofession_supplement_the_profession_of_the_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplementprofession',
            options={'ordering': ['name'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='specialization_professions',
            field=models.ManyToManyField(blank=True, null=True, related_name='supplement_user', to='new.supplementprofession'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='supplement_the_profession_of_the_user',
            field=models.ManyToManyField(related_name='supplement_profession', to='new.supplementprofession'),
        ),
    ]
