# Generated by Django 5.2.2 on 2025-07-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0009_alter_supplementprofession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='specialization_professions',
            field=models.ManyToManyField(blank=True, related_name='supplement_user', to='new.supplementprofession', verbose_name='Специализация'),
        ),
    ]
