# Generated by Django 5.2.2 on 2025-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0011_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='knowledge_of_foreign_languages', to='new.language', verbose_name='Язык'),
        ),
    ]
