# Generated by Django 5.2.2 on 2025-07-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0012_myuser_languages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Иностранный язык', 'verbose_name_plural': 'Иностранные языки'},
        ),
        migrations.AddField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('A1', 'начальный'), ('A2', 'элементарный'), ('B1', 'средний'), ('B2', 'выше среднего'), ('C1', 'продвинутый'), ('C2', 'профессиональный')], default='A1', max_length=2, verbose_name='уровень'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='knowledge_of_foreign_languages', to='new.language', verbose_name='Знание языков'),
        ),
    ]
