# Generated by Django 5.2.2 on 2025-07-29 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0013_alter_language_options_language_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='level',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='biological_sex',
            field=models.CharField(blank=True, choices=[('', '— Не выбран —'), ('F', 'женский'), ('M', 'мужской')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='the_level_of_professionalism',
            field=models.CharField(blank=True, choices=[('', '— Нет никакого —'), ('LR', 'ученик'), ('BR', 'начинающий'), ('LL', 'небольшой опыт'), ('EX', 'опыт есть'), ('PR', 'профессионал'), ('SP', 'супер-профессионал'), ('HB', 'хобби')], max_length=2, null=True, verbose_name='Уровень профессионализма'),
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'начальный'), ('A2', 'элементарный'), ('B1', 'средний'), ('B2', 'выше среднего'), ('C1', 'продвинутый'), ('C2', 'профессиональный')], default='A1', max_length=2, verbose_name='уровень знания языка')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.language')),
            ],
            options={
                'verbose_name': 'Иностранный язык',
                'verbose_name_plural': 'Иностранные языки',
                'ordering': ['language', 'level'],
            },
        ),
        migrations.AlterField(
            model_name='myuser',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='knowledge_of_foreign_languages', to='new.languagelevel', verbose_name='Знание языков'),
        ),
    ]
