# Generated by Django 5.2.5 on 2025-08-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0014_course_passion_skill_certificate_course_used_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperOfTheCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link_to_the_original', models.URLField(blank=True, null=True, verbose_name='Ссылка на оригинал')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, choices=[('JN', 'базовый'), ('MD', 'средний'), ('SN', 'продвинутый')], max_length=2, null=True, verbose_name='Уровень владения навыком'),
        ),
        migrations.AddField(
            model_name='course',
            name='the_author_is_a_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new.developerofthecourse', verbose_name='Автор или разработчик'),
        ),
    ]
